### ISSUE TITLE
Skin switching mid-run

### ISSUE THREAD

**Issue by BakkaTaco** [KingEnderBrine/-RoR2-PartialItemDisplay#4] opened 2022-08-04 00:14 UTC
Whenever using a modded skin/color with partial item display mod enabled it seems to switch me to using the vanilla default skin for the character around stages 3-4. Ive tried all sorts of different config settings and mod combinations but nothing seems to fix it. if this is a known occurrence with a solution pls lmk!

**Comment by KingEnderBrine** [comment] 2022-08-04 13:02
Why do you think it's an issue with this mod specifically? It doesn't touch skins in any way

**Comment by BakkaTaco** [comment] 2022-08-04 19:04
The problem always resolves itself when the mod is removed, I've done isolated runs with only a single skin mod and the partialitemdisplay mod (with and without dependencies) and the problem still persists throughout all the skin mods I tested.

**Comment by KingEnderBrine** [comment] 2022-08-05 12:43
Can you reproduce it, then send me the log file?

**Comment by KingEnderBrine** [comment] 2022-08-05 12:47
Because I just quickly jumped through 20 stages (using DebugToolkit) with a modded skin and some items and it didn't change

**Comment by KingEnderBrine** [comment] 2022-08-19 13:00
Closing due to not being able to reproduce and no issue activity

**Closed as completed by KingEnderBrine** 2022-08-19 13:00 UTC
