### ISSUE TITLE
Spectator mode bug fixed but crash.

### ISSUE THREAD

**Issue by benjdidj** [KingEnderBrine/-RoR2-PartialItemDisplay#1] opened 2021-01-04 20:27 UTC
the menu dont show up in inlobby cfg and i am lock in spectator mode. 
I have lots of mods.
heres a config just in and out.
[logoutput.txt](https://github.com/KingEnderBrine/-RoR2-PartialItemDisplay/files/5766652/logoutput.txt)

**Comment by KingEnderBrine** [comment] 2021-01-05 04:14
Can you send me your r2modman profile as a file? Because it works fine for my mod list.

**Comment by KingEnderBrine** [comment] 2021-01-05 04:28
Actually, I've added some checks and published an update, you can check it now

**Comment by benjdidj** [comment] 2021-01-05 05:53
[r2modman list.txt](https://github.com/KingEnderBrine/-RoR2-PartialItemDisplay/files/5768365/r2modman.list.txt)

**Comment by benjdidj** [comment] 2021-01-05 09:16
the spectator mode bug was a conflict with starstorm2. starstorm2 already had a conflict with  another mod before and did the same, i remember now. 

but still not working with my mods,  my game crashed.
No wonder why my game crashes lol :
![Cb31wgD8Nn](https://user-images.githubusercontent.com/72584566/103628171-e694a500-4f3e-11eb-9970-e68cf5e7d526.jpg)
another time they were blazing elite.  on the whole map also.
[logoutput.txt](https://github.com/KingEnderBrine/-RoR2-PartialItemDisplay/files/5769180/logoutput.txt)

**Comment by KingEnderBrine** [comment] 2021-01-05 10:27
Send me your `com.KingEnderBrine.PartialItemDisplay.cfg` file

**Comment by benjdidj** [comment] 2021-01-05 16:19
[com.KingEnderBrine.PartialItemDisplay.txt](https://github.com/KingEnderBrine/-RoR2-PartialItemDisplay/files/5771336/com.KingEnderBrine.PartialItemDisplay.txt)
 made it a txt just for import reason.

**Comment by KingEnderBrine** [comment] 2021-01-06 03:53
Now it should be fixed

**Comment by benjdidj** [comment] 2021-01-06 04:32
yeap looks like it.
 i have the menu. thx.

**Comment by KingEnderBrine** [comment] 2021-01-06 11:55
The crash is most likely not caused by PartialItemDisplay, and you should go with a log to a #tech-support channel in ror modding discord.

**Comment by benjdidj** [comment] 2021-01-06 15:08
The thing is have no crash anymore, that was more a huge freeze actually. Your mod seem to work now since last updtate. However with more than 100 mods active(and beta ones) with no skins(loading the game get too dam long), i am pretty sure there is matter for things going wrong :) maybe ill try to post more logs, but i am always afraid to flood or to be annoying. Also when u dont more than one hour run it's sometimes hard to replicate bugs and to pinpoint what's going on. u surely know better than me. 
feel free to erase this comment, i dont want to flood ur issue tab

**Closed as completed** 2021-01-07 03:44 UTC
